export const ActionTypes = {
    INCREMENT_COUNT : "INCREMENT_COUNT",
    DECREMENT_COUNT : "DECREMENT_COUNT",
    INCREMENT_COUNT_BY_VALUE : "INCREMENT_COUNT_BY_VALUE",
    GET_COUNT : "GET_COUNT",
    DECREMENT_COUNT_BY_VALUE: 'DECREMENT_COUNT_BY_VALUE'
}