export const RoleActions = {
    ADD_ROLE : "ADD_ROLE",
    DELETE_ROLE: "DELETE_ROLE",
    DELETE_PERMISSION : "DELETE_PERMISSION",
    ASSIGN_PERMISSION : "ASSIGN_PERMISSION",
    FETCHING_ROLES: "FETCHING_ROLES"
}